### ISSUE TITLE
how to enable arithmetic calclations with clee?

### ISSUE THREAD

**Issue by TheKvc** [GroophyLifefor/Clee#6]
; sum=!a!+!b!

doesn't transltes to "set /a sum=!a!+!b!" instead it comes to "set sum=!a!+!b!"

now, in batch we know - when we want to make mathematical calculation ans when we just want to save the string to a variable, with the help of '/a' switch.

how in clee, we can define and use it smartly?
can clee detect that on the right hand side of the equation, '+, -, *, / etc. are used so the user want to use "set /a" instead of "set"??

**Comment by GroophyLifefor** [comment]
I can't touch anyone's custom batch code, so I can't manipulate your set command, but I can customize Clee's own variable recognition.
```rust
#Clee
; text=hello world
```
-> 
```cmd
SET text=hello world
```

will now autodetect arithmetic operations and put the /a parameter itself
```rust
#Clee
; sum=!a!+!b!
; sum+=5
; sum<<=15
```
->
```cmd
SET /A sum=!a!+!b!
SET /A sum+=5
SET /A sum<<=15
```
